from fastapi import APIRouter, BackgroundTasks, Depends, File, Form, HTTPException, Query, UploadFile
from fastapi.responses import FileResponse, StreamingResponse
from pydantic import BaseModel
from typing import Optional
from io import BytesIO
from app.core.dependencies import get_current_user
from app.zimbra.client import zimbra_client
from app.repositories.email_state_repo import email_state_repo
from app.repositories.email_summary_repo import email_summary_repo
from app.repositories.activity_log_repo import activity_log_repo
from app.services import ai_service
from app.services.conversation_service import record_sent_email
from app.repositories.conversation_repo import conversation_repo

# Extensions blocked for security — executables and script files
_BLOCKED_EXTENSIONS = {
    '.exe', '.bat', '.sh', '.cmd', '.ps1', '.vbs', '.jar',
    '.msi', '.scr', '.pif', '.com', '.dll', '.reg', '.hta',
    '.wsf', '.php', '.py', '.rb', '.pl', '.cgi',
}
_MAX_FILE_BYTES  = 10 * 1024 * 1024   # 10 MB per file
_MAX_TOTAL_BYTES = 25 * 1024 * 1024   # 25 MB total

router = APIRouter(prefix="/api/emails", tags=["emails"])

# Global set of message_ids currently being summarized — prevents duplicate work
# when the frontend polls GET /api/emails every few seconds.
_summarizing: set[str] = set()

# System senders generated by Zimbra/OS — filtered out of the interface
# (they remain in Zimbra and are visible in the Zimbra admin panel)
_SYSTEM_SENDER_PREFIXES = ("root@", "zimbra@", "postmaster@", "mailer-daemon@", "admin-noreply@")

def _is_system_email(email_dict: dict) -> bool:
    sender = (email_dict.get("from") or "").lower().strip()
    # strip display name if present: "Zimbra <zimbra@host>" → "zimbra@host"
    if "<" in sender:
        sender = sender.split("<")[-1].rstrip(">").strip()
    return any(sender.startswith(p) for p in _SYSTEM_SENDER_PREFIXES)


class SendEmailRequest(BaseModel):
    to:          str
    subject:     str
    body:        str
    original_id: Optional[str] = None
    in_reply_to: Optional[str] = None   # Message-ID of the email being replied to


class EmailActionRequest(BaseModel):
    operation:  str
    folder:     Optional[str] = "INBOX"
    message_id: Optional[str] = None  # Stable RFC 2822 Message-ID for DB persistence


OP_MAP = {
    "read":            "read",
    "unread":          "unread",
    "star":            "star",
    "unstar":          "unstar",
    "delete":          "delete",
    "trash":           "trash",
    "spam":            "spam",
    "not_spam":        "not_spam",
    "trash_from_spam": "trash_from_spam",
    "spam_from_trash":   "spam_from_trash",
    "restore_from_trash": "restore_from_trash",
    "permanent_delete":   "permanent_delete",
}


async def _summarize_missing(user_id: int, emails: list, summaries: dict,
                             username: str = "", role: str = "",
                             email_addr: str = "", password: str = ""):
    """Background task: generate summaries for emails without one.
    Rate control is handled inside ai_service._call_ai (semaphore + sleep).
    Stops immediately if the daily quota is exceeded.
    Auto-moves emails classified as Spam to the Spam folder."""
    for em in emails:
        mid = em.get("message_id", "")
        if not mid or mid in summaries or mid in _summarizing:
            continue
        _summarizing.add(mid)
        try:
            result = await ai_service.summarize_email(
                subject=em.get("subject", ""),
                body=em.get("body", "") or em.get("preview", ""),
                sender=em.get("from", ""),
                username=username,
                role=role,
            )
            await email_summary_repo.upsert(user_id, mid, result)

            # Auto-move to Spam if classified as Spam
            if result.get("category") == "Spam" and email_addr and password:
                email_id = em.get("id", "")
                if email_id:
                    try:
                        await zimbra_client.move_to_spam(email_addr, password, email_id, source="INBOX")
                        print(f"Auto-moved spam email (ID: {email_id}) to Spam folder.", flush=True)
                    except Exception as e:
                        print(f"Failed to auto-move spam email: {e}", flush=True)
        except RuntimeError as e:
            if "daily_quota_exceeded" in str(e):
                print("Daily quota hit — stopping background summarization.", flush=True)
                return   # stop processing the rest of the batch
        except Exception as e:
            print(f"Background summarize error: {e}", flush=True)
        finally:
            _summarizing.discard(mid)


@router.get("")
async def list_emails(
    background_tasks: BackgroundTasks,
    folder: str = Query("INBOX", regex="^(INBOX|STARRED|SENT|SPAM|TRASH)$"),
    limit:  int = Query(100, ge=1, le=500),
    current_user: dict = Depends(get_current_user)
):
    email    = current_user.get("email")
    password = current_user.get("password")
    user_id  = current_user.get("id")
    print(f"Fetching emails for: {email}, folder: {folder}", flush=True)
    try:
        emails = await zimbra_client.get_folder_emails(
            email=email, password=password, folder=folder, limit=limit,
        )
        print(f"Found {len(emails)} emails", flush=True)

        # Filter out Zimbra system notifications (still visible in Zimbra panel)
        if folder == "INBOX":
            before = len(emails)
            emails = [e for e in emails if not _is_system_email(e)]
            if len(emails) < before:
                print(f"Filtered {before - len(emails)} system emails from INBOX", flush=True)

        # Overlay DB-stored read/starred states (DB is source of truth for our app)
        message_ids = [e.get("message_id", "") for e in emails]
        db_states   = await email_state_repo.get_states(user_id, message_ids)
        for em in emails:
            mid = em.get("message_id", "")
            if mid and mid in db_states:
                em["starred"] = db_states[mid]["starred"]
                em["read"]    = db_states[mid]["read"]

        # Overlay AI summaries
        summaries = await email_summary_repo.get_summaries(user_id, message_ids)
        for em in emails:
            mid = em.get("message_id", "")
            if mid and mid in summaries:
                em["ai_title"]    = summaries[mid]["title"]
                em["ai_brief"]    = summaries[mid]["brief"]
                em["ai_category"] = summaries[mid]["category"]

        # Fire background summarization only for INBOX (not SENT/STARRED/SPAM/TRASH)
        if folder == "INBOX":
            username = current_user.get("username", "")
            role     = current_user.get("role", "")
            background_tasks.add_task(_summarize_missing, user_id, emails, summaries, username, role, email, password)

        # Mark which INBOX emails are replies to emails this user sent
        if folder == "INBOX":
            from datetime import datetime
            in_reply_to_vals = [
                e.get("in_reply_to", "").strip()
                for e in emails if e.get("in_reply_to", "").strip()
            ]
            sent_ids = await conversation_repo.check_are_replies(user_id, in_reply_to_vals)
            for em in emails:
                in_rt = em.get("in_reply_to", "").strip()
                is_reply = in_rt in sent_ids
                em["is_important_reply"] = is_reply
                if is_reply:
                    mid = em.get("message_id", "").strip()
                    date_val = em.get("date_ms")
                    edate = datetime.utcfromtimestamp(date_val / 1000) if date_val else datetime.utcnow()
                    await conversation_repo.record_received(
                        user_id=user_id,
                        message_id=mid,
                        in_reply_to=in_rt,
                        email_date=edate,
                        subject=em.get("subject", ""),
                    )
        else:
            for em in emails:
                em["is_important_reply"] = False

        return {"emails": emails, "folder": folder, "count": len(emails)}
    except Exception as e:
        print(f"Error fetching emails: {e}", flush=True)
        return {"emails": [], "folder": folder, "count": 0}


@router.get("/search")
async def search_emails(
    q:      str = Query(..., min_length=1),
    folder: str = Query("INBOX"),
    limit:  int = Query(50, ge=1, le=200),
    current_user: dict = Depends(get_current_user)
):
    email    = current_user.get("email")
    password = current_user.get("password")
    user_id  = current_user.get("id")
    try:
        emails = await zimbra_client.search_emails(
            email=email, password=password, query=q, folder=folder, limit=limit,
        )
        # Overlay DB states on search results too
        message_ids = [e.get("message_id", "") for e in emails]
        db_states   = await email_state_repo.get_states(user_id, message_ids)
        for em in emails:
            mid = em.get("message_id", "")
            if mid and mid in db_states:
                em["starred"] = db_states[mid]["starred"]
                em["read"]    = db_states[mid]["read"]
        return {"emails": emails, "count": len(emails)}
    except Exception as e:
        print(f"Search error: {e}", flush=True)
        return {"emails": [], "count": 0}


@router.get("/{email_id}")
async def get_email_detail(
    email_id: str,
    folder:   str = Query("INBOX"),
    current_user: dict = Depends(get_current_user)
):
    email    = current_user.get("email")
    password = current_user.get("password")
    user_id  = current_user.get("id")
    try:
        detail = await zimbra_client.get_email_detail(
            email=email, password=password, email_id=email_id, folder=folder,
        )
        # Persist read state to DB using stable message_id
        mid = detail.get("message_id", "")
        if mid:
            await email_state_repo.upsert_read(user_id, mid, True)
            # Overlay DB starred state so it matches what the list view shows
            db_states = await email_state_repo.get_states(user_id, [mid])
            if mid in db_states:
                detail["starred"] = db_states[mid]["starred"]
        return detail
    except Exception as e:
        print(f"Detail error: {e}", flush=True)
        raise HTTPException(status_code=404, detail="Email not found")


@router.get("/{email_id}/attachment/{filename}")
async def download_attachment(
    email_id: str,
    filename: str,
    folder: str = Query("INBOX"),
    current_user: dict = Depends(get_current_user),
):
    """Download a single attachment from an email."""
    email    = current_user.get("email")
    password = current_user.get("password")
    try:
        file_data = await zimbra_client.get_attachment(
            email=email, password=password, email_id=email_id,
            filename=filename, folder=folder,
        )
        if not file_data:
            raise HTTPException(status_code=404, detail="Attachment not found")
        return StreamingResponse(
            BytesIO(file_data["content"]),
            media_type=file_data["content_type"],
            headers={"Content-Disposition": f'attachment; filename="{filename}"'},
        )
    except HTTPException:
        raise
    except Exception as e:
        print(f"Attachment download error: {e}", flush=True)
        raise HTTPException(status_code=500, detail="Failed to download attachment")


@router.post("/send")
async def send_email(
    to:          str            = Form(...),
    subject:     str            = Form(...),
    body:        str            = Form(""),
    original_id: Optional[str] = Form(None),
    in_reply_to: Optional[str] = Form(None),
    attachments: list[UploadFile] = File(default=[]),
    current_user: dict = Depends(get_current_user),
):
    email    = current_user.get("email")
    password = current_user.get("password")

    # Security: validate each attachment
    files_data = []
    total_size = 0
    for upload in attachments:
        ext = ('.' + upload.filename.rsplit('.', 1)[-1].lower()) if '.' in upload.filename else ''
        if ext in _BLOCKED_EXTENSIONS:
            raise HTTPException(status_code=422, detail=f'File type "{ext}" is not allowed.')
        data = await upload.read()
        if len(data) > _MAX_FILE_BYTES:
            raise HTTPException(status_code=422, detail=f'"{upload.filename}" exceeds 10 MB limit.')
        total_size += len(data)
        if total_size > _MAX_TOTAL_BYTES:
            raise HTTPException(status_code=422, detail='Total attachments exceed 25 MB.')
        files_data.append((upload.filename, upload.content_type or 'application/octet-stream', data))

    print(f"Sending email from: {email} to: {to}, attachments: {len(files_data)}", flush=True)
    try:
        message_id = await zimbra_client.send_email(
            email=email, password=password,
            to=to, subject=subject, body=body,
            in_reply_to=in_reply_to,
            attachments=files_data,
        )
        if message_id:
            user_id = current_user.get("id")
            await record_sent_email(user_id, message_id, subject)
            await activity_log_repo.log(user_id, "sent", email_id=to, subject=subject, folder="SENT")
            return {"status": "sent", "to": to, "subject": subject}
        raise HTTPException(status_code=500, detail="Failed to send email")
    except HTTPException:
        raise
    except Exception as e:
        print(f"Send error: {e}", flush=True)
        raise HTTPException(status_code=500, detail=f"Failed to send: {str(e)}")


@router.post("/{email_id}/summarize")
async def summarize_email(
    email_id: str,
    folder: str = Query("INBOX"),
    force: bool = Query(False),
    current_user: dict = Depends(get_current_user)
):
    user_id  = current_user.get("id")
    email    = current_user.get("email")
    password = current_user.get("password")

    # Fetch the email to get its content
    detail = await zimbra_client.get_email_detail(
        email=email, password=password, email_id=email_id, folder=folder
    )
    message_id = detail.get("message_id", "")
    if not message_id:
        raise HTTPException(status_code=400, detail="Email has no Message-ID")

    # Check cache first (unless force=true)
    if not force:
        cached = await email_summary_repo.get_summaries(user_id, [message_id])
        if message_id in cached:
            return cached[message_id]

    # Generate and cache
    result = await ai_service.summarize_email(
        subject=detail.get("subject", ""),
        body=detail.get("body", ""),
        sender=detail.get("from", ""),
    )
    await email_summary_repo.upsert(user_id, message_id, result)
    return result


class SmartReplyRequest(BaseModel):
    hint: Optional[str] = ""


@router.post("/{email_id}/smart-replies")
async def get_smart_replies(
    email_id: str,
    folder: str = Query("INBOX"),
    payload: SmartReplyRequest = SmartReplyRequest(),
    current_user: dict = Depends(get_current_user)
):
    email    = current_user.get("email")
    password = current_user.get("password")

    detail = await zimbra_client.get_email_detail(
        email=email, password=password, email_id=email_id, folder=folder
    )
    replies = await ai_service.smart_replies(
        subject=detail.get("subject", ""),
        body=detail.get("body", ""),
        sender=detail.get("from", ""),
        username=current_user.get("username", ""),
        role=current_user.get("role", ""),
        hint=payload.hint or "",
    )
    return {"replies": replies}


@router.post("/{email_id}/action")
async def email_action(
    email_id: str,
    payload:  EmailActionRequest,
    current_user: dict = Depends(get_current_user)
):
    if payload.operation not in OP_MAP:
        raise HTTPException(status_code=400, detail="Invalid operation")
    email      = current_user.get("email")
    password   = current_user.get("password")
    user_id    = current_user.get("id")
    message_id = payload.message_id or ""

    if payload.operation == "read":
        await zimbra_client.mark_as_read(email, password, email_id,
                                         folder=payload.folder or "INBOX")
        await email_state_repo.upsert_read(user_id, message_id, True)
    elif payload.operation == "unread":
        await email_state_repo.upsert_read(user_id, message_id, False)
    elif payload.operation in ("star", "unstar"):
        is_star = payload.operation == "star"
        await zimbra_client.star_email(email, password, email_id, is_star,
                                       folder=payload.folder or "INBOX")
        await email_state_repo.upsert_starred(user_id, message_id, is_star)
    elif payload.operation in ("delete", "trash"):
        src = payload.folder or "INBOX"
        await zimbra_client.move_to_trash(email, password, email_id, source=src)
    elif payload.operation == "trash_from_spam":
        await zimbra_client.move_to_trash(email, password, email_id, source="SPAM")
    elif payload.operation == "spam_from_trash":
        await zimbra_client.move_to_spam(email, password, email_id, source="TRASH")
    elif payload.operation == "spam":
        src = payload.folder or "INBOX"
        await zimbra_client.move_to_spam(email, password, email_id, source=src)
    elif payload.operation == "not_spam":
        await zimbra_client.move_from_spam(email, password, email_id)
    elif payload.operation == "restore_from_trash":
        await zimbra_client.move_from_trash(email, password, email_id)
    elif payload.operation == "permanent_delete":
        await zimbra_client.permanent_delete(email, password, email_id)
        await email_state_repo.delete_state(user_id, message_id)

    _ACTION_LABEL = {
        "read": "read", "unread": "unread",
        "star": "starred", "unstar": "unstarred",
        "delete": "trashed", "trash": "trashed", "trash_from_spam": "trashed",
        "spam": "spam", "spam_from_trash": "spam",
        "not_spam": "not_spam", "restore_from_trash": "restored",
        "permanent_delete": "permanently_deleted",
    }
    # Log the folder where the email now lives so admin can fetch it later
    _DEST_FOLDER = {
        "trash": "TRASH", "delete": "TRASH", "trash_from_spam": "TRASH",
        "spam": "SPAM", "spam_from_trash": "SPAM",
        "restore_from_trash": "INBOX", "not_spam": "INBOX",
    }
    dest_folder  = _DEST_FOLDER.get(payload.operation, payload.folder or "INBOX")
    action_label = _ACTION_LABEL.get(payload.operation, payload.operation)
    await activity_log_repo.log(
        user_id=user_id, action=action_label,
        email_id=email_id, message_id=message_id or None,
        folder=dest_folder
    )
    return {"status": "ok", "operation": payload.operation, "email_id": email_id}
