global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: ailumia-backend
    static_configs:
      - targets: ['ailumia-backend:8000']
    metrics_path: /api/metrics

  - job_name: node
    static_configs:
      - targets: ['ailumia-node-exporter:9100']
